# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "pdf-elements"
SPDX-PackageSupplier = "LibreCode <contact@librecode.coop>"
SPDX-PackageDownloadLocation = "https://github.com/LibreSign/pdf-elements/"

default-license = "AGPL-3.0-or-later"
default-copyright = "2025 LibreCode coop and contributors"

[[annotations]]
path = [
    ".babelrc",
    ".eslintrc.js",
    "env.d.ts",
    "package.json",
    "package-lock.json",
    "postcss.config.js",
    "tsconfig.json",
    "vite.config.ts",
    "vitest.config.ts",
    "examples/**",
    "tests/**",
    "dist/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 LibreCode coop and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 LibreCode coop and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
